---
- name: Check symfony CLI is already installed
  ansible.builtin.shell:
    cmd: symfony -v > /dev/null 2>&1
  register: symfony_installed
  ignore_errors: yes

- debug: var=symfony_installed

- name: Install symfony
  ansible.builtin.shell:
    cmd: wget https://get.symfony.com/cli/installer -O - | bash
  when: symfony_installed.failed
  become: true
  become_user: '{{ os_username }}'

- name: Create link to symfony binary
  file:
    src: "/home/{{ os_username }}/.symfony/bin/symfony"
    dest: "/usr/bin/symfony"
    state: link
  when: symfony_installed.failed
  become: true

- name: Create project
  ansible.builtin.shell:
    cmd: "symfony new --full --no-git /home/{{ os_username }}/{{ project_name }}"
  tags:
    - project

- name: Link composer to the project's binaries directory
  file:
    src: "/home/{{ os_username }}/.symfony/composer/composer.phar"
    dest: "/home/{{ os_username }}/{{ project_name }}/bin/composer"
    state: link
  become: true
  tags:
    - project
