---
- name: Install MariaDB server
  ansible.builtin.apt:
    name: mariadb-server
    state: latest
    allow_unauthenticated: yes
  become: true

- name: Make sure pymysql is present
  become: true
  pip:
    name: pymysql
    state: present

- name: Install mysqld python libary for Ansible
  package:
    name: '{{ mysql_python_package }}'
    state: present
  become: true

- name: Install .my.cnf with credentials
  template:
    src: 'my.cnf.j2'
    dest: '/root/.my.cnf'
    mode: '0400'
  tags: my_cnf
  become: true

- name: Remember to change password
  ansible.builtin.debug:
    msg: 'WARNING - you have to change default mysql_root_password'
  when: mysql_root_password == '123'

- name: "Ensure root password is present"
  mysql_user:
    name: 'root'
    password: '{{ mysql_root_password | mandatory }}'
    state: present
    login_unix_socket: "{{ login_unix_socket | default(omit) }}"
  become: true
  notify:
    - restart mariadb

- name: Database 'test' is absent
  mysql_db:
    name: test
    state: absent
    login_unix_socket: "{{ login_unix_socket | default(omit) }}"
  when: mysql_remove_test_database
  become: true

- name: Ensure anonymous users are absent
  mysql_user:
    name: ''
    state: absent
    host_all: true
    login_unix_socket: "{{ login_unix_socket | default(omit) }}"
  when: mysql_remove_anonymous_users
  become: true

- name: Remove remote root
  community.mysql.mysql_query:
    query:
      - DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1')
    login_unix_socket: "{{ login_unix_socket | default(omit) }}"
  when: mysql_remove_remote_root
  become: true


