---
- name: Add apt repositories
  apt_repository:
    repo: deb https://packages.sury.org/php/ buster main
    state: present
  become: yes

- name: Install PHP
  ansible.builtin.apt:
    name: "{{ item.name }}"
    state: "{{ item.state|default('latest') }}"
    allow_unauthenticated: yes
  loop:
    - { name: php8.0 }
    - { name: php8.0-fpm }
    - { name: php8.0-apcu }
    - { name: php8.0-bcmath }
    - { name: php8.0-curl }
    - { name: php8.0-gd }
    - { name: php8.0-intl }
    - { name: php8.0-mbstring }
    - { name: php8.0-mysql }
    - { name: php8.0-opcache }
    - { name: php8.0-xml }
    - { name: php8.0-zip }
  become: yes

- name: Make php listen local connections
  lineinfile:
    dest: "/etc/php/8.0/fpm/pool.d/www.conf"
    regexp: "listen ="
    line: "listen = 127.0.0.1:9000"
  become: true

- name: Configure overrides
  ansible.builtin.template:
    src: common.ini
    dest: "/etc/php/8.0/mods-available/common.ini"
  become: true

- name: Enable overrides
  file:
    src: "/etc/php/8.0/mods-available/common.ini"
    dest: "/etc/php/8.0/{{ item.dest }}/conf.d/30-common.ini"
    state: link
  loop:
    - { dest: cli }
    - { dest: fpm }
  become: true
  notify: restart php-fpm


